# only for development or testing
version: "2.2"

services:
  nginx:
    image: nginx:latest
    volumes:
     - ./nginx.conf.subpath:/etc/nginx/nginx.conf
    ports:
    - "80:80"

  another-ldap:
    image: shilazi/another-ldap:latest
    environment:
      LDAP_ENDPOINT: "ldaps://testmyldap.com:636"
      LDAP_MANAGER_DN_USERNAME: "CN=john,OU=Administrators,DC=TESTMYLDAP,DC=COM"
      LDAP_BIND_DN: "{username}@TESTMYLDAP.com"
      LDAP_SEARCH_BASE: "DC=TESTMYLDAP,DC=COM"
      LDAP_SEARCH_FILTER: "(sAMAccountName={username})"
      LOG_LEVEL: "DEBUG"
      LOG_FORMAT: "JSON"
      BRUTE_FORCE_PROTECTION: "False"
      BRUTE_FORCE_EXPIRATION: "5"
      BRUTE_FORCE_FAILURES: "3"
      COOKIE_NAME: "another-ldap"
      # shared with subdomian
      COOKIE_DOMAIN: ".example.org"
      # secure only work with https
      COOKIE_SECURE: "False"
      METADATA_TITLE: "Another LDAP"
      METADATA_IMAGE: ""
      METADATA_DESCRIPTION: ""
      METADATA_FOOTER: "Powered by Another LDAP"
      PERMANENT_SESSION_LIFETIME: "7"
      # gunicorn with root path
      SCRIPT_NAME: ""
      LDAP_MANAGER_PASSWORD: "change-me"
      FLASK_SECRET_KEY: "change-me"
    ports:
    - "9000:9000"

  whoami:
    image: jwilder/whoami:latest
    ports:
    - "8000:8000"
